control_configurations:
- name: "watch"
  components:
  - {hardware_interface: "ur3_hw",   controller: "js_pub", description: ""}
  - {hardware_interface: "planner_hw", controller: "js_pub", description: ""}
  - {hardware_interface: "ur3_hw", controller: "ft_pub", description: ""}

- name: "ctrl"
  depends: ["watch"]
  hidden: true  # do not appear in the gui
  components:
  - {hardware_interface: "ur3_hw", controller: "ctrl1", description: ""}

- name: "posvel_ctrl"
  depends: ["watch"]
  hidden: true  # do not appear in the gui
  components:
  - {hardware_interface: "ur3_hw", controller: "posvel_ctrl", description: ""}

- name: "posvel_ctrl_planner"
  depends: ["posvel_ctrl"]
  hidden: true  # do not appear in the gui
  components:
  - {hardware_interface: "planner_hw", controller: "microinterpolator", description: ""}

- name: "trajectory_tracking"
  depends: ["ctrl"]
  components:
  - {hardware_interface: "planner_hw", controller: "microinterpolator", description: ""}

- name: simple_touch
  depends: ["cartesian_velocity"]
  components:
  - {hardware_interface: "planner_hw", controller: "simple_touch", runtime_check: false}

- name: cartesian_velocity
  depends: ["watch"]
  components:
  - {hardware_interface: "ur3_hw", controller: "cartesian_velocity",  runtime_check: false}

- name: cartesian_position
  depends: ["watch"]
  components:
    - {hardware_interface: "ur3_hw", controller: "cartesian_position",  runtime_check: true}
