planner_hw:
  remap_source_args:
  - "/planner_hw/js_pub/joint_states"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/cancel"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/feedback"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/goal"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/result"
  - "/planner_hw/microinterpolator/follow_joint_trajectory/status"
  - "/planner_hw/microinterpolator/unscaled_joint_target"
  - "/planner_hw/microinterpolator/execution_ratio"

  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/cancel"
  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/feedback"
  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/goal"
  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/result"
  - "/planner_hw/microinterpolator_impedance/follow_joint_trajectory/status"
  - "/planner_hw/microinterpolator_impedance/unscaled_joint_target"
  - "/planner_hw/microinterpolator_impedance/execution_ratio"

  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/cancel"
  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/feedback"
  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/goal"
  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/result"
  - "/planner_hw/microinterpolator_elastoplastic/follow_joint_trajectory/status"
  - "/planner_hw/microinterpolator_elastoplastic/unscaled_joint_target"
  - "/planner_hw/microinterpolator_elastoplastic/execution_ratio"

  - "/planner_hw/simple_touch/simple_touch/cancel"
  - "/planner_hw/simple_touch/simple_touch/feedback"
  - "/planner_hw/simple_touch/simple_touch/goal"
  - "/planner_hw/simple_touch/simple_touch/result"
  - "/planner_hw/simple_touch/simple_touch/status"
  - "/planner_hw/replanner/follow_joint_trajectory/cancel"
  - "/planner_hw/replanner/follow_joint_trajectory/feedback"
  - "/planner_hw/replanner/follow_joint_trajectory/goal"
  - "/planner_hw/replanner/follow_joint_trajectory/result"
  - "/planner_hw/replanner/follow_joint_trajectory/status"
  - "/planner_hw/replanner/unscaled_joint_target"


  remap_target_args:
  - "/joint_states"
  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"
  - "/unscaled_joint_target"
  - "/execution_ratio"

  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"
  - "/unscaled_joint_target"
  - "/execution_ratio"

  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"
  - "/unscaled_joint_target"
  - "/execution_ratio"

  - "/simple_touch/cancel"
  - "/simple_touch/feedback"
  - "/simple_touch/goal"
  - "/simple_touch/result"
  - "/simple_touch/status"
  - "/manipulator/follow_joint_trajectory/cancel"
  - "/manipulator/follow_joint_trajectory/feedback"
  - "/manipulator/follow_joint_trajectory/goal"
  - "/manipulator/follow_joint_trajectory/result"
  - "/manipulator/follow_joint_trajectory/status"
  - "/unscaled_joint_target"

  js_pub:
    # type:         ros/control/JointStatePublisher
    type:         cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: "base_link"
    tool_link: "tool0"
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning

  microinterpolator:
    type: "cnr/control/ScaledFJTPosVelEffController"
    controlled_joints: all
    continuity_order: 1
    goal_tolerance: 0.0001
    path_tolerance: 0.001
    check_tolerance: true
    pub_log_target: true
    clik_gain: 0.0

  simple_touch:
    type: cnr/control/SimpleTouchController
    sensor_name : "wrench"
    base_link   : "base_link"
    tool_link   : "tool0"
    sensor_frame: "tool0"
    output_twist_ns: "/target_cart_twist"
